name: caffeinated
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  velocity_x: 3.6.0
  get_storage: 2.0.3
  simple_animations: 5.0.0+3
  retrofit: 3.3.1
  dio: 4.0.6
  freezed_annotation: 2.2.0
  dartz: 0.10.1
  animate_do: 3.0.2
  card_swiper: ^2.0.4
  google_fonts: 4.0.1
  cached_network_image: 3.2.3
  firebase_core: 2.4.1
  firebase_messaging: 14.2.1
  flutter_local_notifications: 13.0.0
  esewa_flutter_sdk: 
    path: ./esewa_flutter_sdk
  flutter: 
    sdk: flutter

dependency_overrides:
  intl: ^0.18.0

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  retrofit_generator: ^4.2.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

